In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Import CSV file

file1 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2010.DP02_data_with_overlays_2020-03-17T221905.csv"
file2 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2011.DP02_data_with_overlays_2020-03-17T221905.csv"
file3 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2012.DP02_data_with_overlays_2020-03-17T221905.csv"
file4 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2013.DP02_data_with_overlays_2020-03-17T221905.csv"
file5 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2014.DP02_data_with_overlays_2020-03-17T221905.csv"
file6 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2015.DP02_data_with_overlays_2020-03-17T221905.csv"
file7 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2016.DP02_data_with_overlays_2020-03-17T221905.csv"
file8 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2017.DP02_data_with_overlays_2020-03-17T221905.csv"
file9 = "../Resources/Census.gov/DP02_Language_Household_Education/ACSDP1Y2018.DP02_data_with_overlays_2020-03-17T221905.csv"

data1 = pd.read_csv(file1)
data_2010 = pd.DataFrame(data1).transpose()
data_2010.head()

,0,1
GEO_ID,id,1600000US4805000
NAME,Geographic Area Name,"Austin city, Texas"
DP02_0003E,Estimate!!HOUSEHOLDS BY TYPE!!Family household...,88908
DP02_0003PE,Percent!!HOUSEHOLDS BY TYPE!!Family households...,27.5
DP02_0004E,Estimate!!HOUSEHOLDS BY TYPE!!Family household...,112882

In [5]:
test_file = "../Resources/Census.gov/Test_Delimited.csv"

data3 = pd.read_csv(test_file)
data_df = pd.DataFrame(data3)
data_df

,GEO_ID,id,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,1600000US4805000
0,NAME,Geographic Area Name,NaN,NaN,NaN,NaN,"Austin city, Texas"
1,DP02_0003E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),With own children under 18 years,NaN,88908
2,DP02_0003PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),With own children under 18 years,NaN,27.5
3,DP02_0004E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,NaN,112882
4,DP02_0003M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),With own children under 18 years,NaN,3707
5,DP02_0003PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),With own children under 18 years,NaN,1.2
6,DP02_0004M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,NaN,4055
7,DP02_0001E,Estimate,HOUSEHOLDS BY TYPE,Total households,NaN,NaN,323282
8,DP02_0004PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,NaN,34.9
9,DP02_0006E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",NaN,15801
10,DP02_0007M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",With own children under 18 years,1581
11,DP02_0001M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Total households,NaN,NaN,4713
12,DP02_0004PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,NaN,1.2
13,DP02_0005E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,With own children under 18 years,54045
14,DP02_0007PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",With own children under 18 years,2.4
15,DP02_0001PE,Percent,HOUSEHOLDS BY TYPE,Total households,NaN,NaN,323282
16,DP02_0006M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",NaN,1972
17,DP02_0007PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",With own children under 18 years,0.5
18,DP02_0001PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Total households,NaN,NaN,(X)
19,DP02_0005M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,With own children under 18 years,3229
20,DP02_0002E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),NaN,NaN,170844
21,DP02_0006PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",NaN,4.9
22,DP02_0002M,Estimate Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),NaN,NaN,4290
23,DP02_0002PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),NaN,NaN,52.8
24,DP02_0005PE,Percent,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,With own children under 18 years,16.7
25,DP02_0006PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",NaN,0.6
26,DP02_0002PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),NaN,NaN,1.3
27,DP02_0005PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Family households (families),Married-couple family,With own children under 18 years,1
28,DP02_0007E,Estimate,HOUSEHOLDS BY TYPE,Family households (families),"Male householder, no wife present, family",With own children under 18 years,7622
29,DP02_0013PM,Percent Margin of Error,HOUSEHOLDS BY TYPE,Households with one or more people under 18 years,NaN,NaN,1.2
...,...,...,...,...,...,...,...
567,DP02_0058PE,Percent,EDUCATIONAL ATTAINMENT,Population 25 years and over,NaN,NaN,502032
568,DP02_0058PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,Population 25 years and over,NaN,NaN,(X)
569,DP02_0059E,Estimate,EDUCATIONAL ATTAINMENT,Less than 9th grade,NaN,NaN,41150
570,DP02_0059M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,Less than 9th grade,NaN,NaN,4139
571,DP02_0059PE,Percent,EDUCATIONAL ATTAINMENT,Less than 9th grade,NaN,NaN,8.2
572,DP02_0059PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,Less than 9th grade,NaN,NaN,0.8
573,DP02_0060E,Estimate,EDUCATIONAL ATTAINMENT,"9th to 12th grade, no diploma",NaN,NaN,31270
574,DP02_0060M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,"9th to 12th grade, no diploma",NaN,NaN,3230
575,DP02_0060PE,Percent,EDUCATIONAL ATTAINMENT,"9th to 12th grade, no diploma",NaN,NaN,6.2
576,DP02_0060PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,"9th to 12th grade, no diploma",NaN,NaN,0.6
577,DP02_0061E,Estimate,EDUCATIONAL ATTAINMENT,High school graduate (includes equivalency),NaN,NaN,86897
578,DP02_0061M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,High school graduate (includes equivalency),NaN,NaN,5081
579,DP02_0061PE,Percent,EDUCATIONAL ATTAINMENT,High school graduate (includes equivalency),NaN,NaN,17.3
580,DP02_0061PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,High school graduate (includes equivalency),NaN,NaN,1
581,DP02_0062E,Estimate,EDUCATIONAL ATTAINMENT,"Some college, no degree",NaN,NaN,97036
582,DP02_0062M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,"Some college, no degree",NaN,NaN,5406
583,DP02_0062PE,Percent,EDUCATIONAL ATTAINMENT,"Some college, no degree",NaN,NaN,19.3
584,DP02_0062PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,"Some college, no degree",NaN,NaN,1.1
585,DP02_0063E,Estimate,EDUCATIONAL ATTAINMENT,Associate's degree,NaN,NaN,26415
586,DP02_0063M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,Associate's degree,NaN,NaN,2767
587,DP02_0063PE,Percent,EDUCATIONAL ATTAINMENT,Associate's degree,NaN,NaN,5.3
588,DP02_0063PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,Associate's degree,NaN,NaN,0.6
589,DP02_0064E,Estimate,EDUCATIONAL ATTAINMENT,Bachelor's degree,NaN,NaN,138296
590,DP02_0064M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,Bachelor's degree,NaN,NaN,6120
591,DP02_0064PE,Percent,EDUCATIONAL ATTAINMENT,Bachelor's degree,NaN,NaN,27.5
592,DP02_0064PM,Percent Margin of Error,EDUCATIONAL ATTAINMENT,Bachelor's degree,NaN,NaN,1.2
593,DP02_0065E,Estimate,EDUCATIONAL ATTAINMENT,Graduate or professional degree,NaN,NaN,80968
594,DP02_0065M,Estimate Margin of Error,EDUCATIONAL ATTAINMENT,Graduate or professional degree,NaN,NaN,4850
595,DP02_0065PE,Percent,EDUCATIONAL ATTAINMENT,Graduate or professional degree,NaN,NaN,16.1
596,DP02_0018PE,Percent,RELATIONSHIP,Householder,NaN,NaN,41.8